// Список 50 самых распространённых языков.
// code   — код языка (ISO 639-1), используется как ключ в locales.json
// name   — название на английском (для промпта AI и как подпись)
// native — название на самом языке (для селектора в настройках)
// locale — BCP-47 локаль для форматирования дат (toLocaleDateString)
export const LANGUAGES = [
  { code: "en", name: "English", native: "English", locale: "en-US" },
  { code: "zh", name: "Chinese (Simplified)", native: "中文", locale: "zh-CN" },
  { code: "hi", name: "Hindi", native: "हिन्दी", locale: "hi-IN" },
  { code: "es", name: "Spanish", native: "Español", locale: "es-ES" },
  { code: "fr", name: "French", native: "Français", locale: "fr-FR" },
  { code: "ar", name: "Arabic", native: "العربية", locale: "ar-SA" },
  { code: "bn", name: "Bengali", native: "বাংলা", locale: "bn-BD" },
  { code: "pt", name: "Portuguese", native: "Português", locale: "pt-PT" },
  { code: "ru", name: "Russian", native: "Русский", locale: "ru-RU" },
  { code: "ur", name: "Urdu", native: "اردو", locale: "ur-PK" },
  { code: "id", name: "Indonesian", native: "Bahasa Indonesia", locale: "id-ID" },
  { code: "de", name: "German", native: "Deutsch", locale: "de-DE" },
  { code: "ja", name: "Japanese", native: "日本語", locale: "ja-JP" },
  { code: "sw", name: "Swahili", native: "Kiswahili", locale: "sw-KE" },
  { code: "mr", name: "Marathi", native: "मराठी", locale: "mr-IN" },
  { code: "te", name: "Telugu", native: "తెలుగు", locale: "te-IN" },
  { code: "tr", name: "Turkish", native: "Türkçe", locale: "tr-TR" },
  { code: "ta", name: "Tamil", native: "தமிழ்", locale: "ta-IN" },
  { code: "vi", name: "Vietnamese", native: "Tiếng Việt", locale: "vi-VN" },
  { code: "ko", name: "Korean", native: "한국어", locale: "ko-KR" },
  { code: "fa", name: "Persian", native: "فارسی", locale: "fa-IR" },
  { code: "ha", name: "Hausa", native: "Hausa", locale: "ha-NG" },
  { code: "it", name: "Italian", native: "Italiano", locale: "it-IT" },
  { code: "th", name: "Thai", native: "ไทย", locale: "th-TH" },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી", locale: "gu-IN" },
  { code: "pl", name: "Polish", native: "Polski", locale: "pl-PL" },
  { code: "uk", name: "Ukrainian", native: "Українська", locale: "uk-UA" },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ", locale: "kn-IN" },
  { code: "ml", name: "Malayalam", native: "മലയാളം", locale: "ml-IN" },
  { code: "my", name: "Burmese", native: "မြန်မာဘာသာ", locale: "my-MM" },
  { code: "ro", name: "Romanian", native: "Română", locale: "ro-RO" },
  { code: "nl", name: "Dutch", native: "Nederlands", locale: "nl-NL" },
  { code: "am", name: "Amharic", native: "አማርኛ", locale: "am-ET" },
  { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ", locale: "pa-IN" },
  { code: "az", name: "Azerbaijani", native: "Azərbaycan", locale: "az-AZ" },
  { code: "or", name: "Odia", native: "ଓଡ଼ିଆ", locale: "or-IN" },
  { code: "ku", name: "Kurdish", native: "Kurdî", locale: "ku-TR" },
  { code: "el", name: "Greek", native: "Ελληνικά", locale: "el-GR" },
  { code: "cs", name: "Czech", native: "Čeština", locale: "cs-CZ" },
  { code: "sv", name: "Swedish", native: "Svenska", locale: "sv-SE" },
  { code: "hu", name: "Hungarian", native: "Magyar", locale: "hu-HU" },
  { code: "he", name: "Hebrew", native: "עברית", locale: "he-IL" },
  { code: "zu", name: "Zulu", native: "isiZulu", locale: "zu-ZA" },
  { code: "sr", name: "Serbian", native: "Српски", locale: "sr-RS" },
  { code: "fi", name: "Finnish", native: "Suomi", locale: "fi-FI" },
  { code: "bg", name: "Bulgarian", native: "Български", locale: "bg-BG" },
  { code: "da", name: "Danish", native: "Dansk", locale: "da-DK" },
  { code: "sk", name: "Slovak", native: "Slovenčina", locale: "sk-SK" },
  { code: "no", name: "Norwegian", native: "Norsk", locale: "no-NO" },
  { code: "uz", name: "Uzbek", native: "Oʻzbek", locale: "uz-UZ" },
];
